### ISSUE TITLE
Chapter 5 Text and Code Don't Match

### ISSUE THREAD

**Issue by moreli** [OpenCVBlueprints/OpenCVBlueprints#1]
The book text in page 190 calls for a -images switch, but the code is looking for a -output switch
### Book:
>
First, parse the content of your positive image folder to a  le (by using the supplied folder_listing software inside the object annotation folder), and then follow this by executing the annotation command:
      ` ./folder_listing –folder <folder> -images <images.txt>`

### Code:
Line 38 in folder_listing.cpp
```
        }else if( !strcmp( argv[i], "-output" ) )
        {
            output = argv[++i];
        }
```

**Comment by StevenPuttemans** [comment]
Hello @moreli and thank you for pointing this out. As it is easier to adapt the code, I will make the changes to this code in the upcoming days. Thank you for reporting.

Could you also report this at Packt Publishing and refer to this issue tracker?

Thank you in advance! Hope you like the book.

**Comment by moreli** [comment]
Hi @StevenPuttemans. Will follow up with Packt. I'm still going through the chapter (first one I wanted to try because of a little project I'm working on), and I like the clear description. Good Job.

**Comment by StevenPuttemans** [comment]
:+1:

**Comment by moreli** [comment]
There seems to be several discrepancies between the book and the code. You prefer just to push the changes to match the book? Open a separate issue for each discrepancy?
Page 193 at the bottom calls for a `-file` switch, and count_samples.cpp uses `-annotations`

What's your preferred way of handling these?

**Comment by StevenPuttemans** [comment]
@moreli My apologies for the mismatching, seems that they did not check up on it well enough at Packt. I suggest you add them all here, by editing your opening issue, so I can keep track of them all!

**Comment by moreli** [comment]
@StevenPuttemans no worries. You guys did a good job, just want to make sure you are aware. Will post here any additional findings.

**Comment by StevenPuttemans** [comment]
Both reported discrepancies are fixed in code. Be sure to reopen and report more or fire up a new issue!

**Comment by moreli** [comment]
Hi @StevenPuttemans.
The step 5 in page 190 does not match the code. The book states to provide the text file location created 
in earlier steps. However the code is looking for a folder location and it ignores the file altogether.
### Book
>
Now,  re up the annotation tool with the following command:
      `./object_annotation –images <images.txt> -annotations
       <annotations.txt>`

### Code
```
cout << "USAGE ./opencv_annotation -images <folder location> -annotations <ouput file>" << endl;
```

**Comment by StevenPuttemans** [comment]
Ow damn, that is because I adjusted the official OpenCV interface with an annotation tool where we used the folder approach. Let me see what would be the best way to fix this.

Thanks for the report!

**Comment by StevenPuttemans** [comment]
As you can see [here](https://github.com/OpenCVBlueprints/OpenCVBlueprints/blob/master/chapter_5/source_code/object_annotation/object_annotation.cpp#L184) OpenCV launched a glob function which made this interface quite more straightforward, then when the book chapter was written. At that time I did not know of that function.

It was only when adding the annotation tool to the official opencv repository that I adapted it. I guess I will adapt this code to match the book again and add a notice that their is a more evolved version available at [the OpenCV repository](https://github.com/Itseez/opencv/tree/master/apps/annotation).

BTW for future usage when you install OpenCV with its application, you should simply run

`opencv_annotation`

instead of the custom for this chapter built

`./object_annotation` 

which uses a similar approach.

**Comment by StevenPuttemans** [comment]
Problem solved: https://github.com/OpenCVBlueprints/OpenCVBlueprints/commit/2bc08364abaf46b1a9f166e154f34b7f35640a81
