### ISSUE TITLE
ORB descriptor can't work

### ISSUE THREAD

**Issue by Naylor95023** [OpenCVBlueprints/OpenCVBlueprints#12]
when running "fingerprint_process", I found orb_descriptor that's under "feature2d.hpp", 
seems "xfeatures2d.hpp" does not  use? (my opencv version is 3.1.0)
And "orb_descriptor->compute(input_thinned, keypoints, descriptors);"
this line will throw a exception :
-----------------------------------------------------------------------------------------------
C:\buildslave64\win64_amdocl\master_PackSlave-win64-vc14-shared\opencv\modules\features2d\src\orb.cpp:997: error: (-215) level >= 0 in function cv::ORB_Impl::detectAndCompute
-----------------------------------------------------------------------------------------------
I don't know what they mean...can't solve it.
Does I use the wrong library? This version's method has some changes?
Would anyone help me~Please!

**Comment by StevenPuttemans** [comment]
Hi @Naylor95023. In order to build the software needed for Chapter 6 of the OpenCV Blueprints book, you need to make sure that OpenCV is built with the `opencv_contrib` modules, especially the `opencv_xfeatures2d` module. How to do so can be read [here](https://github.com/OpenCVBlueprints/OpenCVBlueprints/blob/master/installation_tutorials/installation_linux.md). This software will thus **NOT** work with any prepacked opencv installation or download.

Just confirmed, by building a clean OpenCV installation myself, master branch of both repos, with `xfeatures2d` selected and the sample runs just fine.
