### ISSUE TITLE
i cannot install open cv on ubuntu14.04

### ISSUE THREAD

**Issue by mecccu** [OpenCVBlueprints/OpenCVBlueprints#13]
I read the step by step guide and I am stuck at the directory explanation.
my root folder is " /home/koj"
when I made a directory named "opencv" in that root directory  and inside that "build" and inside that "opencv_contrib" as explained in the guide.
and then if I try 
 git clone https://github.com/Itseez/opencv.git opencv
then there comes an error that there already exist opencv directory and not empty
So I executed 
git clone https://github.com/Itseez/opencv.git opencv 
in the root directory (" /home/koj") without creating (a directory named "opencv" and inside that "build" and inside that "opencv_contrib") that directory chain and 
after downloading the file in root directory I could find that there is an "opencv" directory made by downloading itself.
So I add "build" directory  and then at that build directory I executed
git clone https://github.com/Itseez/opencv_contrib.git opencv_contrib
then there was automatically made directory in the "build" directory named "opencv_contrib".

So after that I went to build directory and executed "cmake-gui .."
but the return was cmake-gui:cannot connect to x server

And I cannot find any answer at googling.
Please help me to install opencv.
I am at chapter 1 and cannot progress anymore.

**Comment by JoeHowse** [comment]
Hi, mecccu.  The error `cmake-gui:cannot connect to x server` suggests that the X server GUI environment is missing or has some problem.  Are you running on Ubuntu Server or another non-graphical environment?

**Comment by mecccu** [comment]
![20160829_120517](https://cloud.githubusercontent.com/assets/21294401/18039863/d917f19a-6de1-11e6-8257-80e971cb7795.jpg)

**Comment by JoeHowse** [comment]
Pressing Ctrl+Alt+F1 exits the desktop environment (and that's why cmake-gui can't find X server).  Instead, you should just open a Terminal window.  Press Ctrl+Alt+T or follow the instructions here: https://help.ubuntu.com/community/UsingTheTerminal.

**Comment by mecccu** [comment]
![20160829_123213](https://cloud.githubusercontent.com/assets/21294401/18040125/09cc12f0-6de5-11e6-95bc-79d0214e3c81.jpg)
I tried another method from youtube but same result.
before doing step by step of this tutorial I installed at the desktop gui screen of ubuntu the cmake and g++ which was not explained in this tutorial.
And what is the root directory means in this tutorial is that mean really the most deep level? meaning "/"?
or any directory we can start from and then making "opencv" and then inside it "build" and inside it "opencv-contrib"

**Comment by JoeHowse** [comment]
First, you should work in a Terminal window inside the desktop environment, as described in my previous post.

Then, you should install all the dependencies as described in the "Preparing your system" section of the tutorial.  These dependencies include cmake and build-essential.  (g++ is part of build-essential.)  Because you say you didn't find cmake installation in the tutorial, I think you missed this section so please go back and install all the dependencies described in the "Preparing your system" section.

"Root directory" in the tutorial can be any directory you choose.  For example, let's say it's your user directory, ~.  Then, you will end up with the following folders:

~/opencv
~/opencv/build
~/opencv_contrib

**Comment by mecccu** [comment]
hi
I installed all the command in the preparing your system section before following tutorial.
Currently I tried some build process by doing make command.but after that when i tried "cmake-gui .."
in the build directory same reply comes out x server cannot be connected
![20160829_130618](https://cloud.githubusercontent.com/assets/21294401/18040552/f59cc1a8-6de9-11e6-9f5f-54c949ee6995.jpg)

**Comment by JoeHowse** [comment]
As I mentioned previously, the problem with X server is that you've exited the desktop environment (by pressing Ctrl+Alt+F1).  Reboot into the desktop environment and open a Terminal _window_ by pressing Ctrl+Alt+T (or by following the instructions here: https://help.ubuntu.com/community/UsingTheTerminal).

**Comment by mecccu** [comment]
Thank you very much that solved the problem.
I am new to linux and I just googled how to get to console screen and somebody told me press ctrl alt f1
and that was the problem.following figure shows the screen .
![ubuntu 64-bit 3 -2016-08-29-13-23-08](https://cloud.githubusercontent.com/assets/21294401/18040700/d0c95c86-6deb-11e6-998d-28aebdcbabfd.png)
thanks for helping me.I am a newcomer to opencv.

**Comment by StevenPuttemans** [comment]
@mecccu good to see your issue got resolved. A good advice to you would be to first of all take a quick course in Linux/Ubuntu. For example, [this one](http://www.makeuseof.com/tag/ubuntu-an-absolute-beginners-guide/) seems fairly good! 

@JoeHowse thanks for picking this one up.

I will close this down since the issue seems to be resolved.
