### ISSUE TITLE
Chapter 5 object_annotation not working as expected

### ISSUE THREAD

**Issue by jfisher4** [OpenCVBlueprints/OpenCVBlueprints#17]
Hello, I am trying to follow along with chapter 5 and am having problems with the object annotation code. I am using Ubuntu 14.04.05 and have installed opencv 3.1.  I cloned the entire OpenCVBlueprints rep. and once inside the object annotation dir I compiled the code by doing 

cmake .
make

Then I made sure that I had some images handy in the ~/Pictures dir.

When I execute the command

./object_annotation -images ~/Pictures/ -annotations ~/Pictures/annotation.txt

the terminal simply returns to a new prompt with out providing any errors or feedback. 

However if I run the code provided by opencv

./opencv_annotation -images ~/Pictures/ -annotations ~/Pictures/annotation.txt

everything works as expected

Any Ideas?

Thanks,

Ryan

**Comment by StevenPuttemans** [comment]
Hello @jfisher4 and welcome to our github repo. There is indeed a difference between the OpenCV repo and the code found here. That being said `./opencv_annotation -images ~/Pictures/ -annotations ~/Pictures/annotation.txt` will not work any longer on the OpenCV 3.x repo since the tool has been updated to use the more generic cmdLineParser interface. It should now be `./opencv_annotation --images=~/Pictures/ --annotations=~/Pictures/annotation.txt`.

As to the code found here, can you try the following things

- Replace the `~` by its absolute counterpart, which is `/home/username/`
- Can you provide the annotation.txt tool and a small part of your set, so I can test it here locally why it would not work if the above does not solve it?

**Comment by jfisher4** [comment]
Hi Steven thanks for the reply. I was able to follow along with the chapter (5) using the opencv_annotation provided with opencv 3.1 along with the other modules.
